version: "3.9"

services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c " python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=35.238.89.98
      - DB_NAME=devdb
      - DB_USER=ashish
      - DB_PASS=Ashish@2022
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=ashish
      - POSTGRES_PASSWORD=Ashish@2022
    ports:
      - "5432:5432"
volumes:
  dev-db-data: